etworks:
  network-games:
    driver: bridge
    internal: true
  network-panel:
    driver: bridge
  network-playit:
    driver: bridge

services:
  mcsm-daemon:
    image: githubyumao/mcsmanager-daemon:latest
    container_name: mcsm-daemon
    restart: unless-stopped
    environment:
      - MCSM_DOCKER_WORKSPACE_PATH=/opt/mcsmanager/daemon/data/InstanceData
    ports:
      - "24444:24444"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mcsmanager/daemon/data:/opt/mcsmanager/daemon/data
      - /opt/mcsmanager/daemon/logs:/opt/mcsmanager/daemon/logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network-games
      - network-panel

  mcsm-web:
    image: githubyumao/mcsmanager-web:latest
    container_name: mcsm-web
    restart: unless-stopped
    ports:
      - "23333:23333"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mcsmanager/web/data:/opt/mcsmanager/web/data
      - /opt/mcsmanager/web/logs:/opt/mcsmanager/web/logs
    networks:
      - network-panel

  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.17
    container_name: playit-tunnel
    restart: unless-stopped
    environment:
      - SECRET_KEY=
    networks:
      - network-games
      - network-playit
